// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCarousel: typeof import('element-plus/es')['ElCarousel']
    ElCarouselItem: typeof import('element-plus/es')['ElCarouselItem']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElFooter: typeof import('element-plus/es')['ElFooter']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElMenuItemGroup: typeof import('element-plus/es')['ElMenuItemGroup']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSkeleton: typeof import('element-plus/es')['ElSkeleton']
    ElSkeletonItem: typeof import('element-plus/es')['ElSkeletonItem']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    Icons: typeof import('./src/components/common/icons/Icons.vue')['default']
    Loading: typeof import('element-plus/es')['ElLoadingDirective']
    LoadingItem: typeof import('./src/components/common/loading/LoadingItem.vue')['default']
    MainNavBar: typeof import('./src/components/content/mainNavBar/MainNavBar.vue')['default']
    MainTabBar: typeof import('./src/components/content/mainTabBar/MainTabBar.vue')['default']
    ManyButton: typeof import('./src/components/common/button/ManyButton.vue')['default']
    NavBar: typeof import('./src/components/common/navbar/NavBar.vue')['default']
    Progress: typeof import('./src/components/common/progress/Progress.vue')['default']
    TabBar: typeof import('./src/components/common/tabbar/TabBar.vue')['default']
    TabBarItem: typeof import('./src/components/common/tabbar/TabBarItem.vue')['default']
  }
}

export { }
